### ISSUE TITLE
undefined method `bright' 

### ISSUE THREAD

**Issue by kdmsnr** [logaling/logaling-command#98]
```sh
loga import --list
/Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/logaling-command-0.2.3/lib/logaling/command/application.rb:107:in `block in import': undefined method `bright' for "debian_project":String (NoMethodError)
	from /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/logaling-command-0.2.3/lib/logaling/command/application.rb:107:in `each'
	from /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/logaling-command-0.2.3/lib/logaling/command/application.rb:107:in `import'
	from /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/logaling-command-0.2.3/bin/loga:24:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.2.0/bin/loga:23:in `load'
	from /Users/user/.rbenv/versions/2.2.0/bin/loga:23:in `<main>'
```

**Comment by kou** [comment]
報告ありがとうございます！
修正しました！
